const users = [
  {
    name: "John Doe",
    googleId: "550e8400-e29b-41d4-a716-446655440000",
    email: "johndoe@example.com",
    password: "hashedpassword123",
    gender: "male",
    avatar: "",
    verified: true,
    watching: [],
    watched: [],
    saved: [],
    role: "user",
    verificationToken: null,
    verificationExpire: null,
    passwordResetToken: null,
    passwordResetExpire: null,
  },
  {
    name: "Jane Smith",
    googleId: null,
    email: "janesmith@example.com",
    password: "hashedpassword456",
    gender: "female",
    avatar: "",
    verified: false,
    watching: [],
    watched: [],
    saved: [],
    role: "admin",
    verificationToken: "e3b0c442-98fc-1c14-9af1-4b3b9d2f3c5f",
    verificationExpire: "2025-03-12T10:00:00.000Z",
    passwordResetToken: null,
    passwordResetExpire: null,
  },
  {
    name: "Alice Johnson",
    googleId: "c3b8a34d-8765-4a1b-b4f5-8dfb3d1f2c7e",
    email: "alicejohnson@example.com",
    password: "hashedpassword789",
    gender: "female",
    avatar: "",
    verified: true,
    watching: [],
    watched: [],
    saved: [],
    role: "instructor",
    verificationToken: null,
    verificationExpire: null,
    passwordResetToken: "3b1d5f47-9abc-4e2d-8e1a-5d3c8f2b6a9d",
    passwordResetExpire: "2025-03-15T12:00:00.000Z",
  },
];

export default users;
